site_name: Scripted Performances
repo_url: https://github.com/olliepalmer/phd
site_url: https://phd.olliepalmer.com
theme:
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - toc.integrate
markdown_extensions:
  - footnotes
  - toc:
      permalink: "#"
plugins:
  - git-revision-date
extra:
  social:
    - icon: fontawesome/bolt
      link: https://olliepalmer.com
      name: www.olliepalmer.com
    - icon: fontawesome/envelope
      link: mailto:thesis@olliepalmer.com?
      name: send me an email
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_olliepalmer
      name: _olliepalmer on twitter
    - icon: fontawesome/brands/github
      link: https://github.com/olliepalmer
      name: olliepalmer on github


extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2017 - 2022 Ollie Palmer
